import ex25evenmorepractice
sentence = "All good things come to those who wait."
words = ex25evenmorepractice.break_words(sentence)
print(words)
sorted_words = ex25evenmorepractice.sort_words(words)
print(sorted_words)
ex25evenmorepractice.print_first_word(words)
ex25evenmorepractice.print_last_word(words)
print(words)
ex25evenmorepractice.print_first_word(sorted_words)
ex25evenmorepractice.print_last_word(sorted_words)
print(sorted_words)
sorted_words = ex25evenmorepractice.sort_sentence(sentence)
print(sorted_words)
ex25evenmorepractice.print_first_and_last(sentence)
ex25evenmorepractice.print_first_and_last_sorted(sentence)